# Generated by Django 4.0.3 on 2022-03-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_event_created_event_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'date', 'ordering': ['date']},
        ),
    ]
