# Generated by Django 4.0.3 on 2022-03-18 19:34

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='admission_information',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='history',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='legal',
            name='privacy_policy',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='legal',
            name='terms',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ptameetingresolution',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
