# Generated by Django 4.0.3 on 2022-03-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_about_admission_information_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequentlyaskedquestion',
            old_name='title',
            new_name='question',
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FrequentlyAskedQuestionDescription',
        ),
    ]
