# Generated by Django 4.0.3 on 2022-03-22 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_legal_alter_schoolcontactinfo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='about',
            name='vision',
        ),
    ]
