# Generated by Django 4.0.3 on 2022-03-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_picture_delete_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequentlyaskedquestion',
            options={'verbose_name': 'Frequently Asked Question', 'verbose_name_plural': 'Frequently Asked Questions'},
        ),
        migrations.AlterModelOptions(
            name='ptamanagement',
            options={'verbose_name': 'PTA Management', 'verbose_name_plural': 'PTA Management'},
        ),
    ]
