# Generated by Django 4.0.3 on 2022-03-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_frequentlyaskedquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptameetingresolution',
            options={'verbose_name': 'PTA Meeting Resolution', 'verbose_name_plural': 'PTA Meeting Resolutions'},
        ),
        migrations.AlterField(
            model_name='schoolmanagement',
            name='role',
            field=models.CharField(choices=[('L', 'Leadership Team'), ('T', 'Teachers'), ('A', 'Teaching Assistants'), ('O', 'Office Staff'), ('S', 'Support Staff')], max_length=1),
        ),
    ]
