# Generated by Django 4.0.3 on 2022-03-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_schoolmanagement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='admission_information_image',
            field=models.ImageField(default='', upload_to='about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='history_image',
            field=models.ImageField(default='', upload_to='about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='welcome_note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='welcome_note_image',
            field=models.ImageField(default='', upload_to='about'),
            preserve_default=False,
        ),
    ]
