# Generated by Django 4.0.3 on 2022-04-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_about_admission_information_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='history_title',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
