# Generated by Django 4.0.3 on 2022-04-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_about_history_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='application',
            name='areas_of_assistance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='child_id_document',
            field=models.FileField(default='', upload_to='documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='father_contact_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='father_id_document',
            field=models.FileField(default='', upload_to='documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='mother_contact_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_id_document',
            field=models.FileField(default='', upload_to='documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='special_assitance',
            field=models.BooleanField(blank=True, default=False, help_text='Click if the child needs any special assitance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(help_text='format: Surname, Firstname Middlename', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='pupil_class',
            field=models.CharField(choices=[('C1', 'Creche One'), ('C2', 'Creche Two'), ('C3', 'Creche Three'), ('N1', 'Nursery One'), ('N2', 'Nursery Two'), ('N3', 'Nursery Three'), ('P1', 'Primary One'), ('P2', 'Primary Two'), ('P3', 'Primary Three'), ('P4', 'Primary Four'), ('P5', 'Primary Five'), ('P6', 'Primary Six')], max_length=2),
        ),
    ]
