# Generated by Django 4.0.3 on 2022-06-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_application_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='father_id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='application',
            name='mother_id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
