# Generated by Django 4.0.3 on 2022-07-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_application_father_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category_sibling_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='dob_sibling_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='gender_sibling_1',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='sibling_class_1',
            field=models.CharField(blank=True, choices=[('C1', 'Creche One'), ('C2', 'Creche Two'), ('C3', 'Creche Three'), ('N1', 'Nursery One'), ('N2', 'Nursery Two'), ('N3', 'Nursery Three'), ('P1', 'Primary One'), ('P2', 'Primary Two'), ('P3', 'Primary Three'), ('P4', 'Primary Four'), ('P5', 'Primary Five'), ('P6', 'Primary Six')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='sibling_name_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
