# Generated by Django 4.0.3 on 2022-06-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
